### ISSUE TITLE
Use named functions for model constructors

### ISSUE THREAD

**Issue by mwolson** [ticketmaster-api/sdk-javascript#15]
For models like this:

``` js
var Subgenre = function() {
  this.id = undefined;
  this.name = undefined;
};
```

It would be better to define them like this:

``` js
function Subgenre() {
  this.id = undefined;
  this.name = undefined;
}
```

This has the advantage of attaching a name to instances of this class when viewing memory usage statistics, like when you attach the Chrome debugger to a running node.js server which uses this library, which can be useful in tracking down memory leaks.

**Comment by adammeghji** [comment]
This is an excellent suggestion @mwolson :)  

@oliverturner, is this also achieved in https://github.com/ticketmaster-api/sdk-javascript/pull/19?

**Comment by oliverturner** [comment]
It isn't, mainly because #19 dispenses with models (for now)

**Comment by oliverturner** [comment]
Suggest closing this as functions are automatically exported as named during Babel transpilation

**Comment by adammeghji** [comment]
Sounds good, @mwolson can you try now on `2.0.2` and confirm this works for you?

**Comment by mwolson** [comment]
Seems OK, closing out
