### ISSUE TITLE
Any interest in adding ESLint?

### ISSUE THREAD

**Issue by oliverturner** [ticketmaster-api/sdk-javascript#18]
Contributions adhering to the project's style would be easier to make given an ESLint config that matches it.

Is there any appetite to add one, and if so what would your preference be? Personally I'm a fan of Standard (plus semi-colons as here) or AirBnB configs.

**Comment by adammeghji** [comment]
This is a fabulous idea -- love it!  Great call. 

Thanks for implementing this in https://github.com/ticketmaster-api/sdk-javascript/pull/19, we can close this issue after merging that.

**Comment by oliverturner** [comment]
Closing as a consequence of #19 getting merged :)
